POST http://localhost:3000/create-auth-user
content-type: application/json

{
    "email": "pepe@claro.com",
    "password": "prueba123"
}

###
POST http://localhost:3000/sign-in-user
content-type: application/json

{
    "email": "pepe@claro.com",
    "password": "prueba123"
}

###
POST https://cable-net-backend.onrender.com/create-auth-user
content-type: application/json

{
    "email": "juanca@claro.com",
    "password": "prueba123"
}

###
POST https://cable-net-backend.onrender.com/sign-in-user
content-type: application/json

{
    "email": "jose@claro.com",
    "password": "prueba123"
}
